---
env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-var: error
  quotes:
    - error
    - single
  semi:
    - error
    - always
