'use strict';

var _require = require('../../services/translation_service'),
    TranslationService = _require.TranslationService;

var isEdge = window.AW4.Utils.BROWSER.EDGE;
var TRANSLATION_SCOPE = { scope: isEdge ? 'RunnerUploader.edge' : 'RunnerUploader' };

var t = function t(key) {
  return TranslationService.translate(key, TRANSLATION_SCOPE);
};

var template = document.createElement('template');
template.innerHTML = '\n  <style>\n    :host {\n      display: block;\n      position: relative;\n      border: 1px solid #999;\n      height: 500px;\n      width: 100%;\n    }\n\n    :host > * {\n      box-sizing: border-box;\n    }\n\n    :host([incoming][empty]) #incoming {\n      display: flex;\n    }\n\n    :host([incoming][empty]) #empty-dropzone {\n      display: none;\n    }\n\n    :host([empty]) #upload-button {\n      display: none;\n    }\n    :host([empty]) #empty-dropzone {\n      display: flex;\n    }\n\n    :host #files-list {\n      height: 100%;\n      overflow-y: scroll;\n    }\n\n    :host #empty-dropzone {\n      display: none;\n      height: 100%;\n      justify-content: center;\n      align-items: center;\n      flex-direction: column;\n    }\n\n    :host #incoming {\n      align-items: center;\n      display: none;\n      height: 100%;\n      justify-content: center;\n      position: absolute;\n      width: 100%;\n      z-index: 10;\n    }\n\n    :host #error,\n    :host #uploading,\n    :host #upload-complete {\n      display: none;\n      flex: 1;\n      justify-content: space-between;\n    }\n\n    :host([error]) #error {\n      display: flex;\n    }\n\n    :host([uploading]) #uploading {\n      display: flex;\n    }\n    :host([uploading]) #upload-button,\n    :host([uploading]) #add-files-button {\n      display: none;\n    }\n\n    :host([upload-complete]) #upload-complete {\n      display: flex;\n    }\n    :host([upload-complete]) #upload-button,\n    :host([upload-complete]) #add-files-button {\n      display: none;\n    }\n\n    :host footer {\n      background: rgba(0, 0, 0, 0.1);\n      position: absolute;\n      width: 100%;\n      padding: 8px;\n      bottom: 0;\n      display: flex;\n      justify-content: flex-end;\n    }\n\n    :host footer span {\n      flex: 1;\n    }\n  </style>\n\n  <div id="empty-dropzone">\n    <slot name="emptyDropzone">\n      <h1>' + t('emptyHeadingText') + '</h1>\n      <h2>' + t('emptySubheadingText') + '</h2>\n    </slot>\n  </div>\n\n  <div id="incoming">\n    <slot name="incoming">\n      <h1>' + t('incoming') + '</h1>\n    </slot>\n  </div>\n\n  <div id="files-list"></div>\n\n  <footer>\n    <div id="error">\n      <slot name="error">\n        <span>' + t('error') + '</span>\n      </slot>\n    </div>\n\n    <div id="uploading">\n      <slot name="uploading">\n        <span>' + t('uploading') + '</span>\n      </slot>\n    </div>\n\n    <div id="upload-complete">\n      <slot name="uploadComplete">\n        <span>' + t('uploadComplete') + '</span>\n        <button type="button" id="add-more-button">' + t('uploadMore') + '</button>\n      </slot>\n    </div>\n\n    <slot name="addFilesButton">\n      <button type="button" id="add-files-button">' + t('addFiles') + '</button>\n    </slot>\n\n    <slot name="uploadButton">\n      <button type="button" id="upload-button">' + t('upload') + '</button>\n    </slot>\n  </footer>\n';

module.exports = template;